chore: add docker compose override file for local development
openfga/openfga pull request #1015
Opened 2023-09-21 13:27 UTC by sanketrai1

Closes #896

## Description
Adds a `docker-compose.override` file that can be used in conjunction with the existing `docker-compose.yaml` file for applying local development specific build instructions and configuration for services.

## References
https://docs.docker.com/compose/multiple-compose-files/merge/

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2023-09-21 13:33 UTC, sanketrai1 commented
Hi @miparnisari, could you please check if these changes could help in overcoming the issue mentioned in the corresponding issue? Over time more local development-specific changes can be added to the compose override file.

2023-09-25 14:21 UTC, rhamzeh reviewed
@sanketrai1 May I ask if you can add a third option to the "Build from Source" documentation in the README (we can call it: build using docker-compose) which documents how to build it for people other than us who may want to follow?

e.g. `docker compose up -f ... -f ...`

2023-09-25 15:39 UTC, jon-whit commented
> @sanketrai1 May I ask if you can add a third option to the "Build from Source" documentation in the README (we can call it: build using docker-compose) which documents how to build it for people other than us who may want to follow?
> 
> e.g. `docker compose up -f ... -f ...`

From my understanding, and it appears to work this way now as well, Docker looks for `docker-compose.yml` and `docker-compose.override.yml` by default. So nothing changes with the existing documentation around `docker compose up`.

2023-09-25 16:28 UTC, sanketrai1 commented
@rhamzeh, @jon-whit is correct. If `docker-compose.override.yml` is present, then `docker-compose.yml` and `docker-compose.override.yml` are merged automatically when running `docker compose up`. If a compose override file with any other name than `docker-compose.override.yml` or `compose.override.yml` needs to be merged with the default compose file, only then multiple `-f` arguments syntax is needed.

2023-09-27 00:04 UTC, jon-whit commented
@sanketrai1 could you please rebase on `main`?

2023-09-27 13:02 UTC, rhamzeh approved these changes

2023-09-27 14:22 UTC, jpadilla commented
I think the biggest difference when using an override file is that there's no way to skip the overriding. Why not just modify the current docker-compose.yaml file to not use the latest image? Is the intent of the docker-compose setup to get started quick with the latest stable version or with the current version in the filesystem?

2023-10-06 05:53 UTC, miparnisari commented
@rhamzeh our current instructions in the README regarding `docker-compose.yaml` don't really work... see https://github.com/openfga/openfga/issues/1047. Based on the fact that we've had that instruction for a long time now, and we've only noticed now, I think it's fair to assume that nobody is actually using this for setup? 🤷‍♀️

2023-10-06 06:02 UTC, miparnisari commented
@sanketrai1 thanks for submitting this PR! But it doesn't seem to work for me? I removed my OpenFGA containers to start with a clean slate, and I ran `docker-compose up`, and it is using `openfga:openfga/latest`...

2023-10-06 06:10 UTC, miparnisari requested changes
Does this work? See https://github.com/docker/docs/issues/17732

This works for me

```
services:
  migrate:
    image: !reset null
    build: .

  openfga:
    image: !reset null
    build: .
```

But it needs two more changes:

1. Override file must be `.yml`, not `.yaml`
2. I need to run `docker-compose up --build` to trigger a fresh build every time

2023-10-27 13:10 UTC, rhamzeh commented
> `docker-compose up --build` to trigger a fresh build every time (otherwise, first `docker-compose up` triggers a build but subsequent ones do not

This is how docker compose works unfortunately, there is nothing we can do about that. By default it uses the cached build unless you trigger a rebuild.

2023-10-27 13:13 UTC, rhamzeh approved these changes

2023-10-27 19:58 UTC, miparnisari requested changes

2023-10-27 19:58 UTC, miparnisari commented on docker-compose.override.yaml
> +    build: .
```suggestion
services:
  migrate:
    image: !reset null
    build: .

  openfga:
    image: !reset null
    build: .
```

2023-10-27 20:10 UTC, miparnisari approved these changes

2023-10-27 20:11 UTC, jon-whit approved these changes

2023-10-27 20:12 UTC, merged