test: adding unit tests to validate result of read assertion
openfga/openfga pull request #1081
Opened 2023-10-25 23:20 UTC by adriantam

## Description
Update unit test so that we read assertion after write assertion

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2023-10-26 19:49 UTC, miparnisari requested changes

2023-10-26 19:49 UTC, miparnisari commented on pkg/server/test/write_assertions.go
>  func TestWriteAssertions(t *testing.T, datastore storage.OpenFGADatastore) {
```suggestion
func TestWriteAndReadAssertions(t *testing.T, datastore storage.OpenFGADatastore) {
```

2023-10-26 19:49 UTC, miparnisari commented on pkg/server/test/write_assertions.go
>  			err: serverErrors.ValidationError(
Can we move the assertions with `err` to a different test called `TestWriteFailure` so that we don't try to read them?

2023-10-26 19:49 UTC, miparnisari commented on pkg/server/test/write_assertions.go
>  			err: serverErrors.ValidationError(
Another ask: can you add more tests covering

<img width="1697" alt="image" src="https://github.com/openfga/openfga/assets/5374887/f26d8407-2044-4203-a74c-4ddfffa2709f">

2023-10-26 19:49 UTC, miparnisari commented on pkg/server/test/write_assertions.go
Can you also update /pkg/server/test/read_assertions.go? 

<img width="1363" alt="image" src="https://github.com/openfga/openfga/assets/5374887/261cab8f-7f1d-4bd1-a178-a424683f56e0">


Thank you :D

2023-10-30 18:31 UTC, adriantam commented on pkg/server/commands/read_assertions.go
>  	if err != nil {
this check is not needed as the check for assertion model found is in the [server layer](https://github.com/openfga/openfga/blob/1a846a4710fea8d87bb10a1dbee17b7194d3f23b/pkg/server/server.go#L763), not storage layer.

2023-10-30 18:31 UTC, adriantam commented on pkg/server/test/write_assertions.go
>  func TestWriteAssertions(t *testing.T, datastore storage.OpenFGADatastore) {
done

2023-10-30 18:33 UTC, adriantam commented on pkg/server/test/write_assertions.go
Tested as part of [‎TestReadAssertionModelDSError]( https://github.com/openfga/openfga/blob/51b7d9ceee021e42de465720fc64366640ce4daa/pkg/server/server_test.go#L588)

2023-10-30 19:03 UTC, miparnisari commented on pkg/server/server_test.go
> +		curTest := curTest
You don't need this line here. This is only needed with parallel tests. See https://gist.github.com/posener/92a55c4cd441fc5e5e85f27bca008721

2023-10-30 19:04 UTC, miparnisari commented on pkg/server/server_test.go
> +func TestWriteAndReadAssertionModelDSError(t *testing.T) {
These tests aren't calling ReadAssertions

2023-10-30 21:21 UTC, miparnisari approved these changes

2023-10-30 22:46 UTC, merged