refactor: Option builder for command constructors
openfga/openfga pull request #1142
Opened 2023-11-12 18:08 UTC by ilaleksin

## Description

This PR addresses https://github.com/openfga/openfga/issues/1039 adding Options to command constructors

## References

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

2023-11-12 18:13 UTC, ilaleksin commented
server/commands contain structures consisting of only 2 fields: datastore and logger.

For example, **pkg/server/commands/expand.go**
```
type ExpandQuery struct {
	logger    logger.Logger
	datastore storage.OpenFGADatastore
}
```

Do we want to refactor constructors of these structs to use Options as well?
It means, there will be only one option WithLogger.  I am not sure it makes sense to implement Options pattern in the case when we configure only logger.

2023-11-14 21:32 UTC, miparnisari requested changes
Thank you for submitting this!

2023-11-14 21:32 UTC, miparnisari commented on pkg/server/commands/read_changes.go
> +	//logger logger.Logger, encoder encoder.Encoder, horizonOffset int
remove

2023-11-14 21:32 UTC, miparnisari commented on pkg/server/commands/read_changes.go
>  // NewReadChangesQuery creates a ReadChangesQuery with specified `ChangelogBackend` and `typeDefinitionReadBackend` to use for storage
```suggestion
// NewReadChangesQuery creates a ReadChangesQuery with specified `ChangelogBackend`
```

2023-11-14 21:32 UTC, miparnisari commented on pkg/server/commands/write_authzmodel.go
> +func WithWriteAuthModelMaxSize(size int) WriteAuthModelOption {
```suggestion
func WithWriteAuthModelMaxSizeInBytes(size int) WriteAuthModelOption {
```

2023-11-14 21:32 UTC, miparnisari commented on pkg/server/test/read.go
> +				commands.WithReadQueryEncoder(encoder),
I think we can remove these lines and lines 362 and 363 🤔

2023-11-14 21:32 UTC, miparnisari commented on pkg/server/test/read.go
> +		commands.WithReadQueryEncoder(encoder),
Same here, why do we need these if the default is already base 64 encoding?

2023-11-14 21:32 UTC, miparnisari commented on pkg/server/test/read.go
> +	encoder := encoder.NewBase64Encoder()
Can remove

2023-11-14 21:32 UTC, miparnisari commented on pkg/server/test/read_authzmodels.go
> +		commands.WithReadAuthModelsQueryEncoder(encoder),
Can remove

2023-11-14 21:32 UTC, miparnisari commented on pkg/server/test/write_authzmodel.go
> +				commands.WithWriteAuthModelLogger(logger),
Can remove and also remove line 471

2023-11-14 21:32 UTC, miparnisari commented on pkg/server/test/write_assertions.go
> +				commands.WithWriteAuthModelLogger(logger),
Can remove this and line 103

2023-11-14 21:32 UTC, miparnisari commented on pkg/server/test/read_changes.go
> +		readChangesQuery := commands.NewReadChangesQuery(backend, commands.WithReadChangesQueryEncoder(encoder))
This `encoder` is actually an `encrypter`. We don't need this for testing. Can you remove these lines above?

```go
encrypter, err := encrypter.NewGCMEncrypter("key")
require.NoError(t, err)

encoder := encoder.NewTokenEncoder(encrypter, encoder.NewBase64Encoder())
```

Let's just just the default base 64 encoder in tests :)

2023-11-14 21:33 UTC, miparnisari commented
> It means, there will be only one option WithLogger. I am not sure it makes sense to implement Options pattern in the case when we configure only logger.

Yes please, lets implement there too. The less boilerplate we have to write for tests, the better :)

2023-11-20 21:03 UTC, ilaleksin commented
@miparnisari I made the requested changes, please review again.

After I deleted WithOption() calls from the tests **codecov/patch** job in the pipeline started to fail.
Can you help to figure out how to make this job green? (if it is required to merged the PR)

2023-11-20 23:44 UTC, miparnisari approved these changes

2023-11-21 18:28 UTC, merged