chore(tests): update language go module & make DSL in tests more readable
openfga/openfga pull request #1339
Opened 2024-02-05 15:22 UTC by professorabhay

fixes #1302

2024-02-05 15:36 UTC, rhamzeh requested changes

2024-02-05 15:36 UTC, rhamzeh commented on go.mod
> +	github.com/openfga/language v0.0.0-20240205122832-cf938f8254bd // indirect
Is this needed? It is already referenced above as:
```
github.com/openfga/language/pkg/go v0.0.0-20240131004817-1e763f816993
```

Let's update the version there instead

`go get -u github.com/openfga/language/pkg/go`

2024-02-05 16:09 UTC, miparnisari commented
If you search the codebase for this regex

```
^type [^\{(\s]*$
```

that should list all test cases that need to be updated.

2024-02-09 17:13 UTC, jon-whit commented
Let's' focus on the tests in the `pkg/server` and `internal` packages. The models defined elsewhere we can follow up on.

2024-04-17 15:43 UTC, closed without merging

2024-04-17 15:43 UTC, curfew-marathon commented
Thank you for your contribution.  We are going to close this out on account of the unresolved feedback.  At this time the PR is stale.  Feel free to reopen with the requested changes.