fix: forbid conditions that share the same parameter name
openfga/openfga pull request #1359
Opened 2024-02-12 06:24 UTC by edwin-Marrima

## Description
Forbid conditions that share the same parameter names

solves #1286 
## References

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

2024-02-12 14:59 UTC, jon-whit commented on pkg/typesystem/typesystem.go
> +		//validate duplicated conditions parameter
nit - mind adding a space between `// validate`?

2024-02-12 15:00 UTC, jon-whit commented on pkg/typesystem/error.go
> +	//ErrDuplicatedConditionParameterName is return when two or more conditions share the same parameter name.
nit - add space between `// Err` please

2024-02-12 15:03 UTC, jon-whit requested changes
This is a breaking change - we need more discussion and/or coordination before we proceed forward with this.

cc'ing @openfga/backend  more broadly.

2024-02-13 13:08 UTC, miparnisari commented
I don't think it's a breaking change, i would think of it as a bug fix 🤷‍♀️ . If you have a model with clashing parameters today, you are getting errors when calling Check or ListObjects anyway.

2024-02-13 13:58 UTC, edwin-Marrima commented
[miparnisari](https://github.com/miparnisari) With this change in place, If two conditions share the same parameter name with same types it will fail, due this change doesn't check the type (just the parameter name). 

Maybe we should consider checking whether parameters with same name has different types

2024-02-14 05:57 UTC, jon-whit commented
> I don't think it's a breaking change, i would think of it as a bug fix 🤷‍♀️ . If you have a model with clashing parameters today, you are getting errors when calling Check or ListObjects anyway (or you will if you add tuples)

Not necessarily though. Here's an example:

```
model
  schema 1.1

type user

type document
  relations
    define viewer: [user with cond1, user with cond2]

condition cond1(x: int) {
    x < 100
}

condition cond2(x: string) {
    x == "hello"
}
```

If you have the following tuples:
- document:1#viewer@user:jon, condition: cond1
- document:1#viewer@user:maria, condition: cond2

The following Checks are totally acceptable:
`Check(document:1#viewer@user:jon, context: {x: 1})` --> {allowed: true}
`Check(document:1#viewer@user:maria, context: {x: "hello"})` --> {allowed: true}

If we did what this PR says it is doing then we'd be breaking the use case above, and I'm not sure we want to do that.

2024-02-14 23:46 UTC, miparnisari commented
Ok yes in that case it's a breaking change. I'm still okay with this, as long as we call it out on the release notes.

2024-02-15 15:59 UTC, jon-whit commented
> Ok yes in that case it's a breaking change. I'm still okay with this, as long as we call it out on the release notes.

I left a more detailed description of the concern [here](https://github.com/openfga/openfga/issues/1286#issuecomment-1946395136). We just need to make a decision on which approach we want to go. cc'ing @aaguiarz for context.

2024-02-29 16:54 UTC, closed without merging