feat: enable consistency options support by default & disable associated exp flag
openfga/openfga pull request #1889
Opened 2024-08-28 17:41 UTC by rhamzeh

## Description

## References

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2024-08-28 19:25 UTC, ewanharris submitted a review, later dismissed

2024-08-28 19:55 UTC, willvedd approved these changes
LGTM. Next time can we add a description, please 🙏 ??

2024-08-28 20:03 UTC, willvedd requested changes
Change itself looks good. But can you update the unreleased section in the changelog?

2024-08-29 11:51 UTC, willvedd commented on CHANGELOG.md
> +  - See [#1764](https://github.com/openfga/openfga/pull/1764) for full details on this feature
```suggestion
* Consistency options experimental flag has been removed and is now enabled by default. Refer to the [consistency options feature PR](https://github.com/openfga/openfga/pull/1764) for usage details. [#1889](https://github.com/openfga/openfga/pull/1889)
```

2024-08-29 11:52 UTC, willvedd approved these changes
One suggestion. Otherwise, thank you for updating the changelog 🙏

2024-08-29 11:56 UTC, willvedd approved these changes

2024-08-29 14:16 UTC, merged