Update ReadChanges interface for additional flexibility
openfga/openfga pull request #1976
Opened 2024-10-01 16:19 UTC by elbuo8

Allow the changelog to be traversed backwards. 

## Description

## References

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2024-10-01 16:57 UTC, jpadilla approved these changes

2024-10-01 16:58 UTC, jpadilla requested changes
@elbuo8 `TestReadChanges/sort_desc_returns_most_recent_changes_with_object_type_filter` failing test

2024-10-01 18:06 UTC, jpadilla approved these changes

2024-10-01 18:16 UTC, miparnisari approved these changes

2024-10-01 18:21 UTC, merged

2024-10-03 00:32 UTC, miparnisari commented on CHANGELOG.md
> +* `ReadChanges` now supports sorting. [#1976](https://github.com/openfga/openfga/pull/1976)
This is slightly misleading - the API didn't change, only the store adapter did. Could we amend this?