refactor: split the validation to the server specific and binary
openfga/openfga pull request #1998
Opened 2024-10-07 10:10 UTC by arrlancore

## Description

Separate the validation config struct from general `Verify()` into two methods:

`VerifyServerSettings()`: Validates core OpenFGA server functionality settings, including timeouts, concurrent reads, dispatch throttling, and condition evaluation costs.

`VerifyBinarySettings()`: Checks configuration related to how the OpenFGA binary is run, including logging, playground settings, TLS configuration, and request timeouts.

## References

 #1874 
## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2024-10-09 18:00 UTC, adriantam submitted a review, later dismissed

2024-10-15 23:27 UTC, adriantam approved these changes

2024-10-15 23:37 UTC, adriantam requested changes

2024-10-15 23:37 UTC, adriantam commented on internal/server/config/config_test.go
@arrlancore : There are some linter errors, do you mind running make lint to fix these linter errors?  Thank you

2024-10-17 13:50 UTC, arrlancore commented on internal/server/config/config_test.go
yes sure @adriantam

2024-10-19 14:24 UTC, arrlancore commented on internal/server/config/config_test.go
please check again @adriantam 
thanks

2024-10-21 13:56 UTC, adriantam approved these changes

2024-10-21 16:37 UTC, merged