feat: implement dynamic TLS certificate reloading for HTTP and gRPC servers
openfga/openfga pull request #2182
Opened 2024-12-22 13:28 UTC by RokibulHasan7

## Description

## References
 #668

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2025-01-02 14:40 UTC, miparnisari submitted a review, later dismissed
Could you please explain how you tested this PR? I used the "steps to test" in https://github.com/openfga/openfga/pull/696 and this PR doesn't show any logs indicating that the new cert was loaded

2025-01-02 15:25 UTC, RokibulHasan7 commented
> Could you please explain how you tested this PR? I used the "steps to test" in #696 and this PR doesn't show any logs indicating that the new cert was loaded

Generate a pair of TLS certificate and key files in a directory named certs:
```
mkdir certs

openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out certs/tls.crt -keyout certs/tls.key

./openfga run --grpc-tls-enabled --grpc-tls-cert ./certs/tls.crt --grpc-tls-key ./certs/tls.key --http-enabled=false --playground-enabled=false
```
Use openssl to connect to the gRPC endpoint and display the loaded certificates: `openssl s_client -connect localhost:8081 -showcerts`

Now generate a new TLS certificate and key, replacing the existing ones:
```
openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out certs/tls.crt -keyout certs/tls.key
```
Run openssl again to connect to the gRPC endpoint and check if the new certificate was loaded:
`openssl s_client -connect localhost:8081 -showcerts`

2025-01-10 18:24 UTC, jpadilla commented on cmd/run/run.go
> +				cert, err := tls.LoadX509KeyPair(config.GRPC.TLS.CertPath, config.GRPC.TLS.KeyPath)
Does `GetCertificate` run for every request? If so, wouldn't this end up having to load the keypair from disk every time?

2025-01-11 05:04 UTC, RokibulHasan7 commented on cmd/run/run.go
> +				cert, err := tls.LoadX509KeyPair(config.GRPC.TLS.CertPath, config.GRPC.TLS.KeyPath)
Yes, `GetCertificate` is called for every incoming request, which would mean that without optimizations, the keypair would be loaded from disk for each request. This could result in unnecessary overhead. To resolve this, I’ve updated the code to use certwatcher for dynamic certificate loading. PTAL

2025-01-22 21:29 UTC, jpadilla requested changes
I got the following when running this and the provided steps:

```
2025-01-22T16:22:29.955-0500	INFO	🚀 starting gRPC server on '0.0.0.0:8081'...
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
	>  goroutine 97 [running]:
	>  runtime/debug.Stack()
	>  	/opt/homebrew/Cellar/go/1.23.3/libexec/src/runtime/debug/stack.go:26 +0x64
	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	>  	/Users/jose.padilla/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/log/log.go:60 +0xf4
	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0x140006a8f80, 0x7)
	>  	/Users/jose.padilla/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/log/deleg.go:111 +0x30
	>  github.com/go-logr/logr.Logger.Info({{0x102681128?, 0x140006a8f80?}, 0x0?}, {0x101d721f7, 0x1a}, {0x0, 0x0, 0x0})
	>  	/Users/jose.padilla/go/pkg/mod/github.com/go-logr/logr@v1.4.2/logr.go:276 +0x5c
	>  sigs.k8s.io/controller-runtime/pkg/certwatcher.(*CertWatcher).updateCachedCertificate(0x1400017b030, 0x14000d40080, {0x140002dd100, 0xcc8, 0xcc9})
	>  	/Users/jose.padilla/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/certwatcher/certwatcher.go:177 +0x1b8
	>  sigs.k8s.io/controller-runtime/pkg/certwatcher.(*CertWatcher).ReadCertificate(0x1400017b030)
	>  	/Users/jose.padilla/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/certwatcher/certwatcher.go:207 +0x190
	>  sigs.k8s.io/controller-runtime/pkg/certwatcher.(*CertWatcher).Start(0x1400017b030, {0x1026780f8, 0x1400015c100})
	>  	/Users/jose.padilla/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/certwatcher/certwatcher.go:139 +0x2e0
	>  github.com/openfga/openfga/cmd/run.watchAndLoadCertificateWithCertWatcher.func1()
	>  	/Users/jose.padilla/Desktop/openfga-tls/cmd/run/run.go:932 +0x18c
	>  created by github.com/openfga/openfga/cmd/run.watchAndLoadCertificateWithCertWatcher in goroutine 1
	>  	/Users/jose.padilla/Desktop/openfga-tls/cmd/run/run.go:930 +0x2c4
```

2025-01-29 15:24 UTC, jpadilla requested changes

2025-01-29 15:24 UTC, jpadilla commented on cmd/run/run.go
> +	log.SetLogger(klog.Background())
I'd rather see this set only in the context of using certwatcher. Maybe move into `watchAndLoadCertificateWithCertWatcher`? A small comment on _why_ would be appreciate it too, since its not obvious its related to certwatcher.

Also for now we can discard the logs from certwatcher itself.

For example,

```
diff --git a/cmd/run/run.go b/cmd/run/run.go
index 0042810..1587fd0 100644
--- a/cmd/run/run.go
+++ b/cmd/run/run.go
@@ -19,6 +19,7 @@ import (
 	"time"

 	"github.com/cenkalti/backoff/v4"
+	"github.com/go-logr/logr"
 	grpc_ctxtags "github.com/grpc-ecosystem/go-grpc-middleware/tags"
 	grpcauth "github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/auth"
 	grpc_recovery "github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/recovery"
@@ -40,7 +41,6 @@ import (
 	healthv1pb "google.golang.org/grpc/health/grpc_health_v1"
 	"google.golang.org/grpc/reflection"
 	"google.golang.org/grpc/status"
-	"k8s.io/klog/v2"
 	"sigs.k8s.io/controller-runtime/pkg/certwatcher"
 	"sigs.k8s.io/controller-runtime/pkg/log"

@@ -316,7 +316,6 @@ func run(_ *cobra.Command, _ []string) {
 	}

 	logger := logger.MustNewLogger(config.Log.Format, config.Log.Level, config.Log.TimestampFormat)
-	log.SetLogger(klog.Background())
 	serverCtx := &ServerContext{Logger: logger}
 	if err := serverCtx.Run(context.Background(), config); err != nil {
 		panic(err)
@@ -916,6 +915,8 @@ func (s *ServerContext) Run(ctx context.Context, config *serverconfig.Config) er
 }

 func watchAndLoadCertificateWithCertWatcher(ctx context.Context, certPath, keyPath string, logger logger.Logger) (func(*tls.ClientHelloInfo) (*tls.Certificate, error), error) {
+	log.SetLogger(logr.New(nil))
+
 	// Create a certificate watcher
 	watcher, err := certwatcher.New(certPath, keyPath)
 	if err != nil {

```

2025-01-29 15:24 UTC, jpadilla commented on cmd/run/run.go
> +		grpcGetCertificate, err := watchAndLoadCertificateWithCertWatcher(ctx, config.GRPC.TLS.CertPath, config.GRPC.TLS.KeyPath, s.Logger)
Could we gracefully handle errors from `watchAndLoadCertificateWithCertWatcher`, falling back to the behavior prior to these changes?

2025-01-29 17:36 UTC, RokibulHasan7 commented on cmd/run/run.go
> +	log.SetLogger(klog.Background())
Updated.

2025-01-30 15:27 UTC, jpadilla commented on cmd/run/run.go
> +		grpcGetCertificate, err := watchAndLoadCertificateWithCertWatcher(ctx, config.GRPC.TLS.CertPath, config.GRPC.TLS.KeyPath, s.Logger)
@RokibulHasan7 thoughts about this?

2025-01-30 15:45 UTC, RokibulHasan7 commented on cmd/run/run.go
> +		grpcGetCertificate, err := watchAndLoadCertificateWithCertWatcher(ctx, config.GRPC.TLS.CertPath, config.GRPC.TLS.KeyPath, s.Logger)
updated. PTAL

2025-02-04 17:12 UTC, RokibulHasan7 commented
> looks good, thanks! can you update the changelog?

added.

2025-02-04 20:52 UTC, jpadilla approved these changes

2025-02-06 20:51 UTC, jpadilla approved these changes

2025-02-06 20:55 UTC, merged