chore: wire up `runtime.WithStreamErrorHandler`
openfga/openfga pull request #299
Opened 2022-10-19 22:21 UTC by jon-whit

## Description
This PR wires up the grpc-gateway runtime handler for streaming error handling. This is to ensure that the streaming endpoints return the same error codes as expected from the unary endpoints.

## References

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2022-10-19 22:25 UTC, jon-whit commented on server/errors/encoded_errors.go
> +		grpcStatusCode = codes.Unauthenticated
Our error handling must change. This is crazy that we go to a non-canonicalized error code and then back to a canonicalized error code. We way overcomplicated this behavior. Our protocol is grpc, so we should return grpc error status, and we can customize the error messages appropriately.

Let's put this on the backlog to revisit the error code strategy in favor of a more canonicalized grpc error status methodology.

2022-10-19 23:09 UTC, miparnisari approved these changes

2022-10-19 23:33 UTC, miparnisari requested changes
The error responses differ between unary & streaming :(

```
2022/10/19 16:32:26 [DEBUG] GET http://localhost:55647/stores
{"code":"unauthenticated","message":"unauthenticated"}
2022/10/19 16:32:26 [DEBUG] POST http://localhost:55647/stores/01GFS9EMKGY23KN2JJQH6WFPRZ/streamed-list-objects
{"error":{"code":16,"message":"unauthenticated","details":[]}}
```

2022-10-20 15:02 UTC, jon-whit commented
> The error responses differ between unary & streaming, is this ok?
> 
> ```
> 2022/10/19 16:32:26 [DEBUG] GET http://localhost:55647/stores
> {"code":"unauthenticated","message":"unauthenticated"}
> 2022/10/19 16:32:26 [DEBUG] POST http://localhost:55647/stores/01GFS9EMKGY23KN2JJQH6WFPRZ/streamed-list-objects
> {"error":{"code":16,"message":"unauthenticated","details":[]}}
> ```

I don't know a way around that. The response from the grpc streaming endpoint is a `*status.Status`. It differs with the unary because of the custom `HTTPErrorHandler`. We have control over the response body of the error with the custom HTTPErrorHandler in the unary case, but not in the streaming RPC case (AFAIK).

2022-10-20 17:10 UTC, miparnisari approved these changes

2022-10-20 18:22 UTC, merged