docs: v0.3.4 changelog
openfga/openfga pull request #501
Opened 2023-02-02 22:15 UTC by craigpastro

## Description

## References

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2023-02-02 22:28 UTC, rhamzeh requested changes

2023-02-02 22:28 UTC, rhamzeh commented on CHANGELOG.md
> +* The new environment variables should work this time (#498)
```suggestion
* fix: using the new clearer env variables (#498). For the full list of env variables, see [.config-schema.json](https://github.com/openfga/openfga/blob/main/.config-schema.json).
```

2023-02-02 22:28 UTC, rhamzeh commented on CHANGELOG.md
> +* The ReadTuples endpoint has been removed. Please use Read with no tuple key instead. (#495)
```suggestion
* The ReadTuples endpoint has been removed. Please use [Read](https://openfga.dev/api/service#/Relationship%20Tuples/Read) with no tuple key instead. (#495)
 e.g. `POST /stores/<store_id>/read` with `{}` as the body
```

2023-02-03 00:13 UTC, jon-whit commented on CHANGELOG.md
> +* The ReadTuples endpoint has been removed. Please use [Read](https://openfga.dev/api/service#/Relationship%20Tuples/Read) with no tuple key instead. (#495)
Can we put the 'e.g.' bit on a newline so it renders more nicely.

* blah...

  e.g. `POST /stores/<store_id>/read` with `{}` as the body

2023-02-03 00:35 UTC, jon-whit submitted a review, later dismissed

2023-02-03 01:30 UTC, rhamzeh submitted a review, later dismissed

2023-02-03 02:05 UTC, jon-whit commented on CHANGELOG.md
> +* Added OpenTelemetry tracing (#499)
Let's add a quick follow up PR to openfga/openfga.dev that documents how to wire up tracing (including the flags and docker compose if that's what you're using).

2023-02-03 02:05 UTC, jon-whit approved these changes

2023-02-03 19:36 UTC, jon-whit approved these changes

2023-02-03 19:55 UTC, merged